./proj3 ../tests/src0 src0.out
./proj3 ../tests/src1 src1.out
./proj3 ../tests/src2 src2.out
./proj3 ../tests/src3 src3.out
./proj3 ../tests/src4 src4.out
./proj3 ../tests/src5 src5.out
./proj3 ../tests/src6 src6.out
./proj3 ../tests/src7 src7.out
./proj3 ../tests/src8 src8.out
./proj3 ../tests/src9 src9.out
./proj3 ../tests/src10 src10.out
./proj3 ../tests/err1 err1.out
./proj3 ../tests/err2 err2.out
./proj3 ../tests/err_opt1 err_opt1.out
./proj3 ../tests/err_opt2 err_opt2.out
./proj3 ../tests/err_opt3 err_opt3.out
./proj3 ../tests/err_opt4 err_opt4.out
./proj3 ../tests/err_opt5 err_opt5.out
./proj3 ../tests/err_opt6 err_opt6.out